services:
  traefik:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./traefik/certs:/certs:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
    command:
      - --global.checkNewVersion=false
      - --global.sendAnonymousUsage=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=${DOCKER_NETWORK:-nuxtship-dev}
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --api.dashboard=true
      - --api.insecure=true
      - --log.level=INFO
    labels:
      - "traefik.http.routers.traefik.rule=Host(`${PROXY_DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"

  logto:
    ports:
      - "3001:3001"
      - "3002:3002"
    environment:
      # Disable SSL verification for internal requests (dev only - needed for self-signed certs)
      NODE_TLS_REJECT_UNAUTHORIZED: 0

  postgres:
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"
