# Dynamic configuration for local development
# Routes app.nuxtship.dev to local dev server (localhost:3000)
# Generated automatically by setup script

http:
  routers:
    app-local:
      rule: "Host(`app.nuxtship.dev`)"
      tls: true
      service: app-local-service
      entryPoints:
        - websecure
        
  services:
    app-local-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3000"
